id: 0

radius: 0.2

# Setting the Ranges in the planner code will consider the radius 
# DOF must consider robot base dimensions
# Cooky demo hallway is [10, 2.5]
# Turtlebot radius ~ 0.2
# Cooky radius ~ 0.6
DOF_min: [0,    0,  -3.14159]
DOF_max: [5,   3,  3.14159]

# relative to map
start: [0, 1.5, 0]
goal:  [5, 1.5, 0]
