id: 0

radius: 0.275

# Setting the Ranges in the planner code will consider the radius 
# DOF must consider robot base dimensions
# Cooky demo hallway is [10, 2.5]
# Turtlebot radius ~ 0.2
# Cooky radius ~ 0.6
DOF_min: [-4.5,  -1.25,  -3.14159]
DOF_max: [8.5,  1.25,  3.14159]

# relative to map
start: [-4.0, 0, 0]
goal:  [7.5, 0, 0]
