id: 0

# DOF must consider robot base dimensions
# Cooky demo hallway is [10, 2.5]
# Turtlebot radius ~ 0.2
# Cooky radius ~ 0.6
DOF_min: [-4.5,  -1.05,  -3.14159]
DOF_max: [8.5,  0.8,  3.14159]

# relative to map
start: [-4.0, 0, 0]
goal:  [7.5, 0, 0]
